deploy:
  image: alpine:latest
  stage: deploy
  variables:
    GITAPP_URL: https://gitapp.si
    GITAPP_NAME: upn-qr
  tags:
    - exec-docker
  script:
    - apk add nodejs~=17 npm git
    - npm install --global caprover
    - caprover deploy --caproverUrl $GITAPP_URL --appToken $GITAPP_TOKEN --appName $GITAPP_NAME --branch origin/master
  only:
    - master
